server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  instance:
    hostname: registry
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
