server:
  port: 6778
spring:
  application:
    name: synctime
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: synctime
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

