server:
  port: 6788
spring:
  application:
    name: Communication
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: Communication
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ftp:
  server:
    ip: 172.20.120.18
    uname:  root
    password: abc.1231111

